__title__ = "mixvel"
__description__ = "Client for MixVel API"
__url__ = "https://github.com/Hack-The-Travel/mixvel-python-sdk"
__version__ = "0.15.0"
__author__ = "Sergei Popinevskii"
__author_email__ = "sergei@yggdr.io"
